name: Build macOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
        
    - name: Check directory structure
      run: |
        pwd
        ls -la
        cat package.json
        
    - name: Build macOS
      run: |
        npm run build
        echo "Build completed"
        ls -la
        ls -la dist || echo "No dist directory"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload DMG
      uses: actions/upload-artifact@v3
      with:
        name: mac-dmg
        path: dist/*.dmg 