name: Build macOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
        
    - name: Build macOS
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 